fix: Fixes the placeholder text overflow UI bug
guardian/prosemirror-elements pull request #141
Opened 2021-09-30 11:00 UTC by SHession

## What does this change?

This PR fixes a placeholder text overflow issue, causing placeholder text to stretch beyond its bounds. This is achieved through some small styling tweaks.

## How to test

Load the demo page, does the placeholder test reasonably stay within its bounds?

## Images
Before:
![image](https://user-images.githubusercontent.com/4633246/135443070-05e8c20f-ddd5-4914-bd0b-e035a94a38bc.png)

After (is it me or is this an optical illusion?):

![PME_OVerflow](https://user-images.githubusercontent.com/4633246/135442992-eb45c59b-d276-405c-b278-1715bc716d0e.gif)

## Accessibility

- [ ] [Tested with screen reader](https://github.com/guardian/source/blob/main/docs/06-accessibility.md#screen-readers)
- [ ] [Navigable with keyboard](https://github.com/guardian/source/blob/main/docs/06-accessibility.md#keyboard-navigation)
- [ ] [Colour contrast passed](https://github.com/guardian/source/blob/main/docs/06-accessibility.md#colour-contrast)
- [x] [The change doesn't use only colour to convey meaning](https://github.com/guardian/source/blob/main/docs/06-accessibility.md#use-of-colour)
- [ ] [Interactive elements show a focus ring when focused by keyboard](https://github.com/guardian/accessibility/blob/main/editorial-tools-guidelines.md#appendix-the-focus-ring)
- [ ] [Semantic elements have been used where possible](https://github.com/guardian/accessibility/blob/main/editorial-tools-guidelines.md#appendix-semantic-html)

2021-09-30 11:06 UTC, jonathonherbert approved these changes
Looks great – this is a better fix than I had in mind, I had forgotten about `textOverflow`!

Edit: could also sneak in an Agate font whilst we're here?

2021-09-30 11:58 UTC, jonathonherbert requested changes
Haha, the integration tests actually caught a bug – our placeholder is now preventing clicks from focusing our input.

I would have thought `pointer-events: none` would solve, but ... it doesn't. Hm.

2021-10-01 08:46 UTC, jonathonherbert approved these changes
Looks good! I can't see what's changed – what did the trick?

2021-10-01 10:17 UTC, SHession commented
> Looks good! I can't see what's changed – what did the trick?

I was using position absolute to get around issues with the height of the input, this seemed to be the cause of the issue with being able to focus the input (still not sure why). Instead of using position absolute, I used vertical align to prevent descenders increasing the text height, which is a nicer solution.

2021-10-01 10:24 UTC, merged